kind: Service
apiVersion: v1
metadata:
  name: project-test-cloudbuild
spec:
  selector:
     run: project-test-cloudbuild
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer